### ISSUE TITLE
Power API

### ISSUE THREAD

**Issue by JoeZwet** [StellarHorizons/Galacticraft-Rewoven#1]
Take advantage of Cotton's power API to create our own.

**Comment by Boundarybreaker** [comment]
I can probably help with this, since I helped design Cotton Energy. Energy types aren't really that present in the main component, so it might be difficult to do the conversion math of Forge Galacticraft, but I'll talk to my co-dev Falkreon to see what he recommends.

**Comment by Boundarybreaker** [comment]
Cotton Energy uses our Cotton ECS component system, which is kinda similar to Forge's block capabilities but with the caveat that you can have multiple components of the same type on one block. If you wanted to provide an LV energy component, you would use `getComponent(EnergyComponent.class, "cotton:low_voltage")`, for example. For the gJ system, you'd offer components components for all the energy types you wanna support and then pass through a wrapper for a custom EnergyComponent that does the proper scaling. I can help write that when the time comes.

**Comment by JoeZwet** [comment]
ok thanks, I'll look into sorting this out when I get home. Should I just look at some of the mods on the cotton org page to get a basic idea of whats going on?

**Comment by Boundarybreaker** [comment]
We haven't done too much with energy so far; our Minimum Viable Product is gonna be [United Manufacturing](https://github.com/cottonmc/unitedmanufacturing), and w're currently working on getting the base implemented. I'll get a draft of our component containers being implemented soon.
