### ISSUE TITLE
Banner Patterns

### ISSUE THREAD

**Issue by vos6434** [StellarHorizons/Galacticraft-Rewoven#31]
Player Head Banner Pattern
Rocket Banner Pattern
more?
![rocket_pattern](https://user-images.githubusercontent.com/21976486/80040355-cbd5e980-84f1-11ea-9959-5a19d1de6845.png)

**Comment by Boundarybreaker** [comment]
We'll definitely want to use Banner++ for this, due to it working around the enum hell of vanilla banner patterns.

**Comment by vos6434** [comment]
oh god so another dependency

**Comment by Boundarybreaker** [comment]
I mean it's about the same total dependency size as on Forge, just decentralized, since Forge does all this stuff itself.

**Comment by vos6434** [comment]
true

**Comment by haykam821** [comment]
You will also need a shield texture.
