### ISSUE TITLE
Make lunar fall damage line up with Forge version of GC

### ISSUE THREAD

**Issue by TheMCSpacePro** [StellarHorizons/Galacticraft-Rewoven#46]
What new feature(s) would you like added to this mod? Please explain the rationale behind your idea.

Simply as the title says. Since a lunar jump back to the level you jumped from is going to cause fall damage in the Fabric version of  GC but not the Forge version, I simply request that fall damage rates are changed to line up with the Forge version. (Current version: 0.1.0-alpha for 1.16)

**Comment by craftablescience** [comment]
I think this is more of a bug than a feature request. It looks like the gravity is changed, but the fall damage values are the same as in the Overworld.
