### ISSUE TITLE
Shift clicking oxygen mask into slot hardlocks the game.

### ISSUE THREAD

**Issue by TheMCSpacePro** [StellarHorizons/Galacticraft-Rewoven#49]
Galacticraft Rewoven version: 0.2.5-alpha+1.16-pre5

Singleplayer, Multiplayer, or Singleplayer opened to LAN? Singleplayer

Please list the Galacticraft Rewoven addons you have installed
N/A
Please provide your LOG (preferably on [gist](https://gist.github.com) or [pastebin](https://pastebin.com)) and screenshots etc. if applicable
https://paste.ee/p/tm45W   (From what I can tell, the error is at line 1809, or https://paste.ee/p/tm45W#s=0&l=1809)

**Comment by TheMCSpacePro** [comment]
Ok, accoring to the Mod Menu ingame, the version is v0.10-alpha+build.0. I am also on the 7/15/2020 build of the code.

**Comment by craftablescience** [comment]
That's the version for every compiled version of the mod. Try redownloading the project and running it again.

**Comment by marcus8448** [comment]
This bug occurs in (almost) all of our inventories. When slots are locked down to specific items, it causes an infinite loop in `ScreenHandler#method_30010`. I haven't had the time to look into it, so if someone wants to, please do.

**Comment by craftablescience** [comment]
At least it doesn't seem to crash the game, and shift-clicking still works as intended.
