### ISSUE TITLE
The problem with capes

### ISSUE THREAD

**Issue by CammiePone** [StellarHorizons/Galacticraft-Rewoven#54]
So there's a slight problem with adding [capes to Galacticraft Rewoven](https://github.com/StellarHorizons/Galacticraft-Rewoven/issues/9), and that's that it's against [Mojang's ToS](https://account.mojang.com/terms) (need to click on "Show the full terms", and then go to the "Commercial usage guidelines"):
> Therefore, if you comply with and follow the Brand and Asset Usage Guidelines and Naming Guidelines above, YOU MAY:
> - sell cosmetic entitlements, except for "Capes," which we define as anything that attempts to visually emulate the feature of a Minecraft player Cape.

Just wanted to bring that to your attention in case you were unaware. I would hate to see the mod get taken down by Mojang's legal team sometime in the future because of it.

**Comment by craftablescience** [comment]
- The original Galacticraft has capes
- Optifine has capes

We do know the EULA is against capes, but until Mojang actually enforces their EULA, in my opinion they're fine.
If the mod is ever taken down for having capes, we can just remove them and reupload it.

**Comment by CammiePone** [comment]
If you wanna risk it. I wouldn't say the lack of enforcement is a good reason to have them, and I just thought of the idea of having little planets that orbit people's heads instead, which is more thematically appropriate I think.

Good luck, though. I'm hoping Rewoven will address some of the original GC's shortcomings, tbh (mostly the painful grind with little payoff), but I've not looked closely at other posts on the issue tracker, or the planning document (if it's public, as idk if it's even visible to us).

**Comment by marcus8448** [comment]
We actually have already disabled capes in Galacticraft: Rewoven, due to the problems that you've outlined above. Instead of capes, we are looking at different cosmetic features for GC:R's supporters.
