### ISSUE TITLE
NASA Designer/Assembler could be renamed to Rocket Designer/Assembler

### ISSUE THREAD

**Issue by JoeZwet** [StellarHorizons/Galacticraft-Rewoven#55]
Naming them NASA implies that only default and/or NASA themed rockets can be created with them, renaming them to Rocket would fix that issue.

Feedback Needed.

**Comment by marcus8448** [comment]
I agree with this. I have already renamed all 'NASA' blocks to 'rocket' blocks.

**Comment by vos6434** [comment]
I guess this issue is resolved then.
