### ISSUE TITLE
Capes

### ISSUE THREAD

**Issue by vos6434** [StellarHorizons/Galacticraft-Rewoven#9]
Capes

**List:**
- [x] Get a cape implementation
- [x] Make cape textures (or take them from the original repository)
- [x] Decide who gets a cape
- [x] Add in-game cape type config
- [x] Add other features
- [x] Polish up capes/get them done

**Comment by SebaSphere** [comment]
When porting capes over, ([People](url
https://github.com/micdoodle8/Galacticraft/blob/master/capes.txt), [Textures](url
https://github.com/micdoodle8/Galacticraft/blob/master/capes.txt)), fix player list so that it is organized by UUID. Posibility to add ability to remove and change the cape you are displaying from Ingame menus.

**Comment by marcus8448** [comment]
Those are really good ideas! I just need to confirm a few things.
If we do the in-game part, we'll just store the UUID's (right?) and have the capes synced by config.
What options would there be?
For contributor capes, what would pass as a contributor? (Like, would small formatting changes or one line fixes count?)

**Comment by marcus8448** [comment]
Those are really good ideas! I just need to confirm a few things.
If we do the in-game part, we'll just store the UUID's (right?) and have the capes synced by config.
What options would there be?
For contributor capes, what would pass as a contributor? (Like, would small formatting changes or one line fixes count?)

**Comment by marcus8448** [comment]
Those are really good ideas! I just need to confirm a few things.
If we do the in-game part, we'll just store the UUID's (right?) and have the capes synced by config.
What options would there be?
For contributor capes, what would pass as a contributor? (Like, would small formatting changes or one line fixes count?)

**Comment by SebaSphere** [comment]
I’m not too sure how micdoodle does the capes but I know micdoodle doesn’t store who wears a cape locally. Bought a cape awhile back for galacticraft and it takes place as soon as micdoodle adds it to the cape.txt I believe. 

For capes, some sort of ability to disable and enable cape in the main menus for galacticraft just incase you have a cape from another mod like optifine or something. 

We could also approach the issue by having a website you can log in, donate under a email, and have the ability to change username at will.

Contribuator I guess would be anyone who makes significant contribuations within the galacticraft community. Likely all galacticraft addon devs and early contribuator that did a lot for galacticraft are to be considered. Also I’d like to see Galacticraft Central early discord staff and people like that be apart of contribuator. Essentially anyone deemed worthy enough of that for some sort of contribuator cape

@marcus8448

**Comment by marcus8448** [comment]
Yeah, it's not stored locally, I meant only store the uuid online, not uuid and cape type.
I think there's a config option in GC (non fabric) to disable the cape.

**Comment by SebaSphere** [comment]
Hmm where would that be @marcus8448 if you remember? Have a cape myself and I’d like the ability to disable certain mod capes if I buy capes for mods like optifine.

**Comment by marcus8448** [comment]
Capes are done(ish)!
