### ISSUE TITLE
Aluminum Wire held model is too big

### ISSUE THREAD

**Issue by vos6434** [StellarHorizons/Galacticraft-Rewoven#91]
![2021-02-26_13 51 32](https://user-images.githubusercontent.com/21976486/109308320-c47e1b80-7839-11eb-8cd7-224246f86b56.png)
![2021-02-26_13 51 36](https://user-images.githubusercontent.com/21976486/109308322-c5af4880-7839-11eb-95ec-2543a8215f88.png)

**Comment by craftablescience** [comment]
![image](https://user-images.githubusercontent.com/26600014/114514734-9bf38a80-9c09-11eb-8320-e5da451e8b8b.png)

This is currently fixed on `main`, closing.
